channels:
 - conda-forge
 - bioconda
 - r
dependencies:
 - conda-forge::cmake
 - conda-forge::r-essentials
 - conda-forge::r-rgl
 - conda-forge::r-rcpp
 - conda-forge::r-rngtools
 - r::r-stringi
 - conda-forge::r-devtools
 - conda-forge::r-gam
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-biocmanager
 - bioconda::bioconductor-deseq2
 - conda-forge::r-ggplot2
 - bioconda::bioconductor-rsubread
 - bioconda::java-jdk
 - bioconda::bioconductor-iranges
 - conda-forge::r-gplots
 - conda-forge::dask-labextension
 - conda-forge::snakeviz
 - conda-forge::ipywidgets
 - conda-forge::python-graphviz
 - conda-forge::bokeh
 - pip
 - pip:
   - rpy2
   - jupyter_server_proxy
   - multiqc
   - cutadapt
   - "dask[complete]"
   
