channels:
 - conda-forge
 - bioconda
dependencies:
 - conda-forge::cmake
 - conda-forge::r-essentials
 - conda-forge::r-rcpp
 - conda-forge::r-devtools
 - conda-forge::r-gam
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-biocmanager
 - conda-forge::r-ggplot2
 - conda-forge::r-gplots
 - conda-forge::r-stringr
 - conda-forge::r-tidyverse
 - conda-forge::r-readr
 - conda-forge::r-tibble
 - conda-forge::r-rcolorbrewer
 - conda-forge::r-glmpca
 - conda-forge::r-dplyr
 - conda-forge::r-cowplot
 - conda-forge::r-dt
 - conda-forge::r-lattice
 - conda-forge::r-magrittr
 - conda-forge::r-mass
 - conda-forge::r-matrixstats
 - conda-forge::r-poiclaclu
 - conda-forge::r-farver
 - conda-forge::r-matrix.utils
 - conda-forge::r-forcats
 - conda-forge::r-purrr
 - bioconda::bioconductor-apeglm
 - bioconda::bioconductor-s4vectors
 - bioconda::bioconductor-biomart
 - bioconda::bioconductor-deseq2
 - bioconda::bioconductor-fgsea
 - bioconda::bioconductor-rsubread
 - bioconda::java-jdk
 - bioconda::bioconductor-iranges
 - bioconda::bioconductor-biobase
 - bioconda::bioconductor-iranges
 - bioconda::bioconductor-edger
 - bioconda::bioconductor-biocparallel
 - bioconda::bioconductor-genomicranges
 - bioconda::bioconductor-limma
 - bioconda::bioconductor-delayedarray
 - bioconda::bioconductor-biocgenerics
 - bioconda::bioconductor-tximport
 - bioconda::bioconductor-summarizedexperiment
 - pip
 - pip:
   - multiqc==1.10
   - cutadapt


